# HOUSING PRICE PREDICTION ML MODEL

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HousePricePrediction.csv')
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   str
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   str
 5   BldgType      2919 non-null   str
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   str
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), str(4)
memory usage: 352.3 KB

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
df['SalePrice'].isnull().sum()

np.int64(1459)

In [6]:
df['SalePrice'].nunique()

663

In [7]:
df['MSZoning'].isnull().sum()

np.int64(4)

In [8]:
df = df.dropna(subset=['SalePrice'])

In [9]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0.0,953.0,175000.0
1456,1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163.0,1542.0,210000.0
1457,1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0.0,1152.0,266500.0
1458,1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029.0,1078.0,142125.0
1459,1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290.0,1256.0,147500.0

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1460 non-null   int64
 1   MSSubClass    1460 non-null   int64
 2   MSZoning      1460 non-null   str
 3   LotArea       1460 non-null   int64
 4   LotConfig     1460 non-null   str
 5   BldgType      1460 non-null   str
 6   OverallCond   1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   Exterior1st   1460 non-null   str
 10  BsmtFinSF2    1460 non-null   float64
 11  TotalBsmtSF   1460 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), str(4)
memory usage: 176.6 KB

In [11]:
std_lot_area = StandardScaler()
std_year_built = StandardScaler()
std_year_remod = StandardScaler()

In [12]:
df['LotArea'] = std_lot_area.fit_transform(df[['LotArea']])
df['YearBuilt'] = std_year_built.fit_transform(df[['YearBuilt']])
df['YearRemodAdd'] = std_year_remod.fit_transform(df[['YearRemodAdd']])

In [29]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_enco,BldgType_enco,LotConfig_enco
0,0,60,RL,-0.207142,Inside,1Fam,5,1.050994,0.878668,VinylSd,0.0,-0.459303,208500.0,3,0,4
1,1,20,RL,-0.091886,FR2,1Fam,8,0.156734,-0.429577,MetalSd,0.0,0.466465,181500.0,3,0,2
2,2,60,RL,0.073480,Inside,1Fam,5,0.984752,0.830215,VinylSd,0.0,-0.313369,223500.0,3,0,4
3,3,70,RL,-0.096897,Corner,1Fam,5,-1.863632,-0.720298,Wd Sdng,0.0,-0.687324,140000.0,3,0,0
4,4,60,RL,0.375148,FR2,1Fam,5,0.951632,0.733308,VinylSd,0.0,0.199680,250000.0,3,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,-0.260560,Inside,1Fam,5,0.918511,0.733308,VinylSd,0.0,-0.238122,175000.0,3,0,4
1456,1456,20,RL,0.266407,Inside,1Fam,6,0.222975,0.151865,Plywood,163.0,1.104925,210000.0,3,0,4
1457,1457,70,RL,-0.147810,Inside,1Fam,9,-1.002492,1.024029,CemntBd,0.0,0.215641,266500.0,3,0,4
1458,1458,20,RL,-0.080160,Inside,1Fam,6,-0.704406,0.539493,MetalSd,1029.0,0.046905,142125.0,3,0,4
1459,1459,20,RL,-0.058112,Inside,1Fam,6,-0.207594,-0.962566,HdBoard,290.0,0.452784,147500.0,3,0,4

In [14]:
df['LotConfig'].unique()

<ArrowStringArray>
['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3']
Length: 5, dtype: str

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
df['BldgType'].unique()

<ArrowStringArray>
['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs']
Length: 5, dtype: str

In [17]:
df['MSZoning'].unique()

<ArrowStringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str

In [18]:
std_ttl_bsmt_sf = StandardScaler()
df['TotalBsmtSF'] = std_ttl_bsmt_sf.fit_transform(df[['TotalBsmtSF']])

In [20]:
from sklearn.preprocessing import LabelEncoder
mszoning_enco = LabelEncoder()
bldg_type_enco = LabelEncoder()
lot_config_enco = LabelEncoder()
df['MSZoning_enco'] = mszoning_enco.fit_transform(df['MSZoning'])
df['BldgType_enco'] = bldg_type_enco.fit_transform(df['BldgType'])
df['LotConfig_enco'] = lot_config_enco.fit_transform(df['LotConfig'])

In [21]:

df[['LotConfig','LotConfig_enco']].drop_duplicates()

    LotConfig  LotConfig_enco
0      Inside               4
1         FR2               2
3      Corner               0
16    CulDSac               1
333       FR3               3

In [22]:
df[['MSZoning','MSZoning_enco']].drop_duplicates()

    MSZoning  MSZoning_enco
0         RL              3
8         RM              4
30   C (all)              0
47        FV              1
341       RH              2

In [23]:
df[['BldgType','BldgType_enco']].drop_duplicates()

   BldgType  BldgType_enco
0      1Fam              0
9    2fmCon              1
17   Duplex              2
23   TwnhsE              4
56    Twnhs              3

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              1460 non-null   int64
 1   MSSubClass      1460 non-null   int64
 2   MSZoning        1460 non-null   str
 3   LotArea         1460 non-null   float64
 4   LotConfig       1460 non-null   str
 5   BldgType        1460 non-null   str
 6   OverallCond     1460 non-null   int64
 7   YearBuilt       1460 non-null   float64
 8   YearRemodAdd    1460 non-null   float64
 9   Exterior1st     1460 non-null   str
 10  BsmtFinSF2      1460 non-null   float64
 11  TotalBsmtSF     1460 non-null   float64
 12  SalePrice       1460 non-null   float64
 13  MSZoning_enco   1460 non-null   int64
 14  BldgType_enco   1460 non-null   int64
 15  LotConfig_enco  1460 non-null   int64
dtypes: float64(6), int64(6), str(4)
memory usage: 210.8 KB

In [26]:
features = [
    'MSSubClass',
    'MSZoning_enco',
    'LotArea',
    'LotConfig_enco',
    'BldgType_enco',
    'OverallCond',
    'YearBuilt',
    'YearRemodAdd',
    'TotalBsmtSF'   
]
X = df[features]

In [30]:
y = df['SalePrice']

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,train_size=0.7)

In [32]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_enco,BldgType_enco,LotConfig_enco
0,0,60,RL,-0.207142,Inside,1Fam,5,1.050994,0.878668,VinylSd,0.0,-0.459303,208500.0,3,0,4
1,1,20,RL,-0.091886,FR2,1Fam,8,0.156734,-0.429577,MetalSd,0.0,0.466465,181500.0,3,0,2
2,2,60,RL,0.073480,Inside,1Fam,5,0.984752,0.830215,VinylSd,0.0,-0.313369,223500.0,3,0,4
3,3,70,RL,-0.096897,Corner,1Fam,5,-1.863632,-0.720298,Wd Sdng,0.0,-0.687324,140000.0,3,0,0
4,4,60,RL,0.375148,FR2,1Fam,5,0.951632,0.733308,VinylSd,0.0,0.199680,250000.0,3,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,-0.260560,Inside,1Fam,5,0.918511,0.733308,VinylSd,0.0,-0.238122,175000.0,3,0,4
1456,1456,20,RL,0.266407,Inside,1Fam,6,0.222975,0.151865,Plywood,163.0,1.104925,210000.0,3,0,4
1457,1457,70,RL,-0.147810,Inside,1Fam,9,-1.002492,1.024029,CemntBd,0.0,0.215641,266500.0,3,0,4
1458,1458,20,RL,-0.080160,Inside,1Fam,6,-0.704406,0.539493,MetalSd,1029.0,0.046905,142125.0,3,0,4
1459,1459,20,RL,-0.058112,Inside,1Fam,6,-0.207594,-0.962566,HdBoard,290.0,0.452784,147500.0,3,0,4

In [36]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=200,random_state=42)
model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [34]:
y_true = df['SalePrice']

In [38]:
answer = model.predict(X_test)

In [39]:
answer

array([157981.5       , 278503.83      , 130673.        , 130821.44      ,
       279341.12      ,  92249.5       , 275901.5       , 144969.135     ,
        92434.5       , 162219.735     , 129774.5       , 122489.5       ,
       118116.185     , 227765.895     , 188674.89      , 136191.125     ,
       193890.17      , 137590.5       , 121798.25      , 213397.22      ,
       165505.895     , 205755.985     , 175604.82      , 126542.75      ,
       204629.9       , 184605.6       , 188928.585     , 149597.        ,
       203801.75      , 195243.965     , 116495.34      , 251372.35      ,
       238137.22      , 126112.5       , 272905.48      , 151764.125     ,
       133320.97      , 196833.825     , 273566.07      , 121187.555     ,
       127295.42      , 193475.39      , 125578.875     , 389412.165     ,
       126369.        , 133026.555     , 121321.5       , 129533.5       ,
       444636.47      , 131608.75      , 115547.        , 176756.75      ,
       100936.10416667, 208261.275     , 141095.67261905, 287970.005     ,
       180334.735     , 172748.25      , 140249.6       , 111866.98666667,
        83520.36666667, 147502.        , 302637.385     , 267111.555     ,
       372508.895     , 193912.1       , 124678.        , 310715.305     ,
       176360.16      , 166164.91      , 129239.44991667, 123380.75      ,
       126617.75      ,  95174.09833333, 420958.865     , 194469.62      ,
       304801.66      , 269570.        , 137055.25      , 120412.5       ,
       103102.75      ,  85056.75      , 139004.        ,  93938.25      ,
       157175.        , 128130.76      , 272376.565     , 201492.195     ,
       141095.67261905, 185196.445     , 149029.        , 172967.75      ,
       128024.        , 226227.6       , 157816.815     , 190205.265     ,
       150128.295     , 162013.465     , 243998.025     , 196330.595     ,
       155000.575     , 197039.        , 248431.75      , 122006.75      ,
       233373.74      , 107618.25      , 155220.5       , 230339.21      ,
       146650.66      , 176178.75      ,  66074.8       , 142492.3       ,
       150541.        , 152233.44      , 221556.585     , 121094.09      ,
       125095.5       , 116109.67      , 137331.97883333, 372667.265     ,
       169600.08      , 141095.67261905, 198571.18      , 183420.895     ,
       192563.565     , 149262.25      , 195157.79      , 128107.185     ,
       151709.045     , 182381.8       , 177840.37      , 307827.595     ,
       195775.5       , 115471.1       ,  86752.5       , 317620.815     ,
       348503.95      , 128092.        , 230395.315     , 603029.27      ,
       294825.64      , 173387.5       , 168503.31      , 145474.75      ,
       165486.47      , 140259.9       , 165199.02      , 201985.01      ,
       151487.56083333,  72163.935     , 109751.86      , 139805.905     ,
       241901.75      , 133873.035     , 118135.5       , 137271.7       ,
       158198.825     , 143857.75      , 111838.75      , 130456.75      ,
       195899.93      , 142195.525     , 265862.865     , 148441.875     ,
       121004.435     , 136550.        , 202217.275     , 371579.715     ,
       452964.435     , 182476.05      , 329546.625     , 116172.59      ,
       130384.17      , 123596.37033333, 264247.76      , 146813.57      ,
       111380.5       , 183940.395     , 130010.51      , 175017.5       ,
       184072.125     ,  91349.33333333, 157348.35      , 123308.22      ,
       261401.3       , 144183.685     , 238576.22      , 190686.745     ,
       197356.75      ,  89472.5       , 120443.02      , 119320.5       ,
       125983.        , 160665.275     , 197515.94      , 138845.25      ,
       189543.08      ,  97815.435     , 165535.18666667, 126726.25      ,
       222732.        , 194687.15      , 163643.02      , 283125.11      ,
       190221.555     , 146388.685     , 260709.2       , 151214.75      ,
       137824.9       , 123689.75      , 186905.5       , 128520.00916667,
       119108.75      , 168757.39      , 248091.85      , 272611.635     ,
       179072.655     , 139648.5       , 129626.8       , 130080.0325    ,
       137557.12      , 200182.305     , 184297.25      , 111940.06      ,
       265920.255     , 199365.52      ,  83539.59      , 124591.25      ,
       183418.5       , 119360.01      , 121550.5       , 174610.95      ,
       118102.        , 156082.85      , 196401.5       , 146708.        ,
       194583.865     , 173824.625     , 239629.55      , 121094.93333333,
       113138.92      , 166789.395     , 242542.2       , 337694.685     ,
       173362.25      , 138662.37      , 151828.685     , 162355.5       ,
       140931.12      , 103938.39      , 185355.55      , 178662.325     ,
       133407.035     ,  85574.25      , 147877.25      , 144074.82      ,
       122369.77      , 106707.06      , 176780.45      , 280350.4       ,
       359058.7       , 162490.775     , 129274.        , 239222.055     ,
       258394.545     , 232970.445     , 171091.85      , 138785.67261905,
       130455.        , 177821.24      , 377853.525     , 200913.775     ,
       291298.485     , 103641.8425    , 102290.57      , 136106.        ,
       132748.85416667, 285489.7       , 266012.7       , 132926.25      ,
       208582.        ,  92092.        , 195421.08      , 135090.42      ,
       288238.895     , 167890.5       , 218883.5       , 122921.34      ,
       248616.09      , 173985.155     , 141484.86      , 120819.5       ,
       143681.        , 198419.        , 117812.25      , 125979.5       ,
       136408.        , 133330.75      , 180760.135     , 113491.95      ,
       181701.245     , 259014.88      , 137446.55      , 162817.855     ,
       139700.935     , 186690.35      , 157846.375     , 204098.49      ,
       194272.75      , 120882.        , 158780.28      , 224104.575     ,
       112757.36      , 148961.87      , 139471.75      , 191846.97      ,
       172363.415     , 168242.39833333, 277300.31      ,  94200.765     ,
       261296.26      , 153389.125     , 150818.75      , 105470.        ,
       192495.43      , 145757.275     , 140124.20916667, 190571.4       ,
       142337.5       , 123253.        , 143558.2975    , 157351.435     ,
       141046.25      , 194022.175     , 164454.73      , 142020.125     ,
       108497.35      , 115880.21      , 101600.5       , 222007.935     ,
       178289.625     , 131861.        , 128810.94166667, 204379.25      ,
       228307.705     , 310623.475     , 263526.        , 129734.375     ,
       184837.395     , 167048.        , 298976.085     , 437819.275     ,
       268246.28      , 173624.46      , 306856.98      , 183106.645     ,
       140580.985     , 128010.35      , 199096.55      , 309208.945     ,
       189580.275     , 142531.68533333, 288323.92      , 224966.15      ,
       150802.125     , 185784.15      , 150513.25      ,  99610.        ,
       140733.685     , 155377.375     , 153388.75      , 184118.39      ,
       106893.535     , 177877.52      , 156801.125     , 128660.        ,
       182851.435     , 189415.1       ,  91915.        , 193273.8       ,
       158236.125     , 196356.595     , 202540.25      , 203767.55      ,
       132940.905     , 186101.        , 137730.25      , 129936.39      ,
       324016.88      , 142671.625     , 123861.25      , 179329.7       ,
       143964.02      , 296165.715     , 136939.5       , 355700.67      ,
       128198.75      , 141142.64      , 186363.425     , 132143.045     ,
       175499.86      , 349770.055     , 156786.        , 149189.75      ,
       150759.625     , 115481.        , 199769.49      , 194971.        ,
       209037.79      , 214794.865     , 182224.075     , 223120.345     ,
        90433.25      , 246568.545     , 143380.5       , 405302.96      ,
       131587.75      , 318789.04      , 243629.91      , 138267.25      ,
       200030.125     , 261103.04      , 214927.865     , 171794.7       ,
       240208.115     , 123961.43833333, 221129.535     , 179280.7       ,
       187469.53      , 213126.69      , 118868.5       , 140516.75      ,
       206281.25      , 137850.5       , 153519.5       , 230928.42      ,
       158856.395     , 482532.15      , 162866.        ])

In [52]:
y_pred = model.predict(X_train)

In [55]:
from sklearn.metrics import r2_score
r2 = r2_score(y_train,y_pred)

In [54]:
y_pred

array([145641.63571429, 217259.775     , 312296.6       , ...,
       120040.5       , 171783.75      , 182471.48      ], shape=(1021,))

In [46]:
y_train

1452    145000.0
762     215200.0
932     320000.0
435     212000.0
629     168500.0
          ...
1095    176432.0
1130    135000.0
1294    115000.0
860     189950.0
1126    174000.0
Name: SalePrice, Length: 1021, dtype: float64

In [56]:
r2

0.9609148991518106